### ISSUE TITLE
Mumbler/Mozartizer

### ISSUE THREAD

**Issue by dikodam** [OhmNoobs/MemeBot#2]
A given sentence T consisting of words should be transmuted in a way that randomly words are tansmuted to their "mumbled" equivalent, replacing every character in the word to be transmuted with a 'n' or 'm' (picked randomly each).

ex.: "bla1 bla2 bla3" -> "bla1 mmn2 nmn3"

**Comment by hubwoop** [comment]
Implemnted with #bcf1e8deefacb5b5f56a1a79a1bf7db168c6dee0
